#!/usr/bin/expect --

set user "ifireball"
set pwd "b00tPa$$"

#log_user 0

proc usage {} {
    global argv0
    puts "Usage: $argv0 \[<#channel>\] TEXT..."
    exit 1
}

if {$argc < 1} usage
if {[string match "#*" [lindex $argv 0]]} {
    if {$argc < 2} usage
    set channel [lindex $argv 0]
    set argv [lrange $argv 1 end]
} else {
    set channel {}
}
spawn ssh ifireball.dyndns.org telnet localhost 9999
expect "nickname."
send "$user\r"
expect "password."
send "$pwd\r"
expect "joined the party line."
send ".say $channel [join $argv] \r"
expect "Said*\n"
puts "$expect_out(0,string)"
send ".quit\r"
